### ISSUE TITLE
A large enough length causes the program to fail with a MemoryError

### ISSUE THREAD

**Issue by DoomTay** [JustAnotherArchivist/warc-peek#1]
A .bat file containing the line `warc-peek.py www.reddit.com-inf-20180420-085636-7m9j5-00001.warc.gz 2447 1306208683` using [this warc](https://archive.org/download/archiveteam_archivebot_go_20180420200001/www.reddit.com-inf-20180420-085636-7m9j5-00001.warc.gz) produces the following output

```
Traceback (most recent call last):
  File "E:\pocket\warc-peek.py", line 54, in <module>
    for offset in find_offsets(args.warcfile, args.offset, args.length):
  File "E:\pocket\warc-peek.py", line 24, in find_offsets
    buffer = fp.read(length)
MemoryError
```

**Comment by JustAnotherArchivist** [comment]
Sorry, I somehow missed this until now...

Yeah, warc-peek reads the full thing into memory and then searches for positions where a record might start. With your command, that means it reads 1.3 GB of data into memory, which can cause it to exhaust your RAM. If you really mean to find all record offsets in the entire 1.3 GB, I'd recommend looping over the file in chunks of some dozens to perhaps a couple hundred MB. (Note the 512-byte window that is mentioned at the end of the readme though.)
